#! /bin/zsh

echo "Setting up for seminar wriring in directory $PWD."

# ensure WritingTools directory exists, else error and exit
if [[ -d ~/Projects/WritingTools ]]; then
    WTS=~/Projects/WritingTools
else
    echo "Directory ~/Projects/WritingTools not found. Aborting." 1>&2
    exit 1
fi

projectname=`basename "$PWD"`

# get operating system type
# different sed syntax for linux and OS X
if [[ `uname` == 'Linux' ]]; then
    export LINUX=1
else
    export LINUX=0
fi
if [[ `uname` == 'Darwin' ]]; then
    export OSX=1
else
    export OSX=0
fi

# don't copy bib files, just add full path in file.
# echo "Getting Theology.bib..."
# ln -s $WTS/Theology.bib $PWD/.
# echo "Done"

echo "Copying Makefile..."
cp $WTS/SeminarMakefile $PWD/Makefile
echo "Editing Makefile..."
if [[ $LINUX -eq 1 ]]; then
    sed -i "s#myfile#$projectname#gi" Makefile
    # trying to remove symlinks, so remove makefile dependence on .bib file
    # sed -i "s#mybib#Theology#gi" Makefile
elif [[ $OSX -eq 1 ]]; then
    sed -i '' -e "s#myfile#$projectname#g" Makefile
    # trying to remove symlinks, so remove makefile dependence on .bib file
    # sed -i '' -e 's#mybib#Theology#g' Makefile
fi
echo "Done"

echo "Copying Gemfile..."
cp $WTS/SeminarGemfile $PWD/Gemfile
echo "Done"

echo "Copying Guardfile..."
cp $WTS/SeminarGuardfile $PWD/Guardfile
echo "Editing Guardfile"
if [[ $LINUX -eq 1 ]]; then
    sed -i "s#myfile#$projectname#gi" Guardfile
elif [[ $OSX -eq 1 ]]; then
    sed -i '' -e "s#myfile#$projectname#g" Guardfile
fi
echo "Done"

echo "Create markdown file..."
make touch
echo "Done"

echo "Project setup complete."

